### ISSUE TITLE
Divide by zero error, time_start and time_end are integers, need to be floating point

### ISSUE THREAD

**Issue by ninaleechie** [lstrz/dsss-illustrated#1]
New to all of this but had to fix one line to get this project to run in Python 2.7
time_start and time_end need to be float, as is they are integers.  If you change time_start = 0 to time_start = 0.0 and time_end = 1.0 / message... this has fixed the problem and allows code to work.

**Comment by lstrz** [comment]
I fixed it now. Thanks for the report. Python 2.X is deprecated soon anyway, so if you didn't do it previously, think about upgrading to 3.X now. :)

This is, I believe, the first time somebody I don't personally know used code from my GitHub repo, so I sincerely hope you found the it useful!
