### ISSUE TITLE
Is there a way to Generate CDMA signal using this ?

### ISSUE THREAD

**Issue by patel999jay** [lstrz/dsss-illustrated#2]
Its more than question than issue. Can we use this to generate CDMA signal ? If yes than which one is better OFDM or CDMA ?

**Comment by lstrz** [comment]
Same principles are used in CDMA (spreading with PRNs) so parts of the code can surely be reused. Whether to use OFDM or CDMA depends very heavily on the context and the specifics of the system you're dealing with, so I can't give further comments.
